name: nis_q_bank
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_database: ^8.0.0
  flutter_screenutil: ^5.0.0+2
  cached_network_image: ^3.1.0
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Black.otf
        - asset: assets/fonts/HelveticaNeue-Bold.otf
        - asset: assets/fonts/HelveticaNeue-BoldItalic.otf
        - asset: assets/fonts/HelveticaNeue-CondensedBlack.otf
        - asset: assets/fonts/HelveticaNeue-CondensedBold.otf
        - asset: assets/fonts/HelveticaNeue-CondensedLight.otf
        - asset: assets/fonts/HelveticaNeue-CondensedMedium.otf
        - asset: assets/fonts/HelveticaNeue-CondensedRegular.otf
        - asset: assets/fonts/HelveticaNeue-CondensedThin.otf
        - asset: assets/fonts/HelveticaNeue-Light.otf
        - asset: assets/fonts/HelveticaNeue-LightItalic.otf
        - asset: assets/fonts/HelveticaNeue-Medium.otf
        - asset: assets/fonts/HelveticaNeue-Regular.otf
        - asset: assets/fonts/HelveticaNeue-Thin.otf
        - asset: assets/fonts/HelveticaNeue-ThinItalic.otf
        - asset: assets/fonts/HelveticaNeue-UltraLight.otf
        - asset: assets/fonts/HelveticaNeue-UltraLightItalic.otf
